### ISSUE TITLE
FAQ Page 404s

### ISSUE THREAD

**Issue by paked** [hshackers/hshackathons.org#1]
Looks like you are missing [`getinvolved.html`](http://hshackathons.org/getinvoled.html)

**Comment by zachlatta** [comment]
:thumbsup:

On Wed, Feb 3, 2016 at 5:15 PM, Harrison Shoebridge <
notifications@github.com> wrote:

> Looks like you are missing getinvolved.html
> http://hshackathons.org/getinvoled.html
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hshackers/hshackathons.org/issues/1.

## 

Zach Latta
Hack Club | zach@hackclub.io
